version: "3.7"

services:
  db:
    image: mariadb:10.5.8
    restart: unless-stopped
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: agencia-envios-db
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_PASSWORD: 123456789
      MYSQL_USER: agencia-envios
    volumes:
      - ./db-data:/var/lib/mysql
